################################################################################
# Environment script generated by ilcsoft-install on Wed May 28 16:52:47 2014
# for Eutelescope located at [ /data-disk4/tbisanz/sw/ilcsoft/v01-17-05/Eutelescope/trunk ]
################################################################################


#--------------------------------------------------------------------------------
#     Global Environment Variables
#--------------------------------------------------------------------------------
export MAKEOPTS="-j4"
export CXX="g++"
export ILCSOFT_CMAKE="/data-disk4/tbisanz/sw/ilcsoft/v01-17-05/ILCSoft.cmake"
export CC="gcc"
export FC="gfortran"
export ILCSOFT_CMAKE_ENV="/data-disk4/tbisanz/sw/ilcsoft/v01-17-05/ILCSoft.cmake.env.sh"


#--------------------------------------------------------------------------------
#     Eutelescope
#--------------------------------------------------------------------------------
export EUDAQ="/data-disk4/tbisanz/sw/ilcsoft/v01-17-05/Eutelescope/trunk/external/eudaq/v1.2.2"
export MILLEPEDEII="/data-disk4/tbisanz/sw/ilcsoft/v01-17-05/Eutelescope/trunk/external/millepede2/tags/V04-00-02"
export MILLEPEDEII_VERSION="tags/V04-00-02"
export EUDAQ_VERSION="tags/v1.2.2"
export EUTELESCOPE="/data-disk4/tbisanz/sw/ilcsoft/v01-17-05/Eutelescope/trunk"
export PATH="$MILLEPEDEII:$EUTELESCOPE/bin:$PATH"
export LD_LIBRARY_PATH="$EUTELESCOPE/pixgeo/lib:$EUTELESCOPE/lib:$EUDAQ/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     GEAR
#--------------------------------------------------------------------------------
export GEAR="/data-disk4/tbisanz/sw/ilcsoft/v01-17-05/gear/HEAD"
export PATH="$GEAR/tools:$GEAR/bin:$PATH"
export LD_LIBRARY_PATH="$GEAR/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     ROOT
#--------------------------------------------------------------------------------
export ROOTSYS="/data-disk4/tbisanz/sw/ilcsoft/v01-17-05/root/5.34.18"
export PATH="$ROOTSYS/bin:$PATH"
export LD_LIBRARY_PATH="$ROOTSYS/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     CLHEP
#--------------------------------------------------------------------------------
export CLHEP="/data-disk4/tbisanz/sw/ilcsoft/v01-17-05/CLHEP/2.1.3.1"
export CLHEP_BASE_DIR="$CLHEP"
export CLHEP_INCLUDE_DIR="$CLHEP/include"
export PATH="$CLHEP_BASE_DIR/bin:$PATH"
export LD_LIBRARY_PATH="$CLHEP_BASE_DIR/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     RAIDA
#--------------------------------------------------------------------------------
export RAIDA_HOME="/data-disk4/tbisanz/sw/ilcsoft/v01-17-05/RAIDA/v01-06-02"
export PATH="$RAIDA_HOME/bin:$PATH"


#--------------------------------------------------------------------------------
#     Marlin
#--------------------------------------------------------------------------------
export MARLIN="/data-disk4/tbisanz/sw/ilcsoft/v01-17-05/Marlin/v01-05"
export PATH="$MARLIN/bin:$PATH"
export MARLIN_DLL="/data-disk4/tbisanz/sw/ilcsoft/v01-17-05/Eutelescope/trunk/lib/libEutelescope.so:$EUDAQ/lib/libNativeReader.so:$MARLIN_DLL"


#--------------------------------------------------------------------------------
#     LCCD
#--------------------------------------------------------------------------------
export LCCD="/data-disk4/tbisanz/sw/ilcsoft/v01-17-05/lccd/v01-03"


#--------------------------------------------------------------------------------
#     LCIO
#--------------------------------------------------------------------------------
export LCIO="/data-disk4/tbisanz/sw/ilcsoft/v01-17-05/lcio/v02-04-03"
export PATH="$LCIO/tools:$LCIO/bin:$PATH"
export LD_LIBRARY_PATH="$LCIO/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     GSL
#--------------------------------------------------------------------------------
export GSL_HOME="/usr"


#--------------------------------------------------------------------------------
#     CED
#--------------------------------------------------------------------------------
export PATH="/data-disk4/tbisanz/sw/ilcsoft/v01-17-05/CED/v01-09-01/bin:$PATH"


#--------------------------------------------------------------------------------
#     GBL
#--------------------------------------------------------------------------------
export GBL="/data-disk4/tbisanz/sw/ilcsoft/v01-17-05/GBL/V01-16-03"
export LD_LIBRARY_PATH="$GBL/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     CMake
#--------------------------------------------------------------------------------
export PATH="/data-disk4/tbisanz/sw/ilcsoft/v01-17-05/CMake/2.8.12/bin:$PATH"


#--------------------------------------------------------------------------------
#     ILCUTIL
#--------------------------------------------------------------------------------
export ilcutil="/data-disk4/tbisanz/sw/ilcsoft/v01-17-05/ilcutil/v01-01"
export LD_LIBRARY_PATH="$ilcutil/lib:$LD_LIBRARY_PATH"
# --- additional comands ------- 
